
- project:
    check:
      jobs:
        - shake-factory-test
        - shake-factory-docs
    gate:
      jobs:
        - shake-factory-test
        - shake-factory-docs

#    post:
#      jobs:
#        - shake-factory-publish-docs
